version: 2

templates:
  gopath-template: &gopath-template
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/u-root/gobusybox
    environment:
      - GOPATH: "/go"
      - CGO_ENABLED: 0
      - GO111MODULE: "off"

  gomod-template: &gomod-template
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/gobusybox
    environment:
      - CGO_ENABLED: 0
      - GO111MODULE: "auto"

  bazel-template: &bazel-template
    docker:
      - image: l.gcr.io/google/bazel:latest
    working_directory: /go/bazel_gobusybox


workflows:
  version: 2
  build:
    jobs:
      - clean-gopath
      - clean-gomod
      - bazel-build

jobs:
  clean-gopath:
    <<: *gopath-template
    steps:
      - checkout
      - run:
          name: Install dep
          command: |
            wget https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64
            mv dep-linux-amd64 dep
            chmod +x dep
      - run:
          name: Check vendored deps
          command: |
            cd vendortest
            ../dep version
            ../dep status
            ../dep ensure -vendor-only
            git status
            if [[ -n "$(git status --porcelain vendor)" ]]; then
              echo 'vendor/ is out-of-date: run `cd vendortest && dep ensure -vendor-only` and then check in the changes'
              echo 'If `cd vendortest && dep ensure` results in no changes, make sure you are using the latest relase of dep'
              git status --porcelain vendor
              exit 1
            fi
      - run:
          name: vet
          command: |
            go vet ./vendortest/...


  clean-gomod:
    <<: *gomod-template
    steps:
      - checkout
      - run:
          name: go mod tidy
          command: |
            (cd src && go mod tidy && go mod verify)
            (cd modtest && go mod tidy && go mod verify)
            (cd modtest/nestedmod && go mod tidy && go mod verify)
      - run:
          name: vet
          command: |
            (cd src && go vet ./...)
            (cd modtest && go vet ./...)
            (cd modtest/nestedmod && go vet ./...)

  bazel-build:
    <<: *bazel-template
    steps:
      - checkout
      - run:
          name: build busybox
          command: cd src && bazel build //:bb
      - run:
          name: build everything
          command: cd src && bazel build //...
